/* Gerado por ferramentas/montar_dados.py a partir da coleta do Instagram @cidadedoagro_.
   Para corrigir nomes/áreas, edite a tabela POSTS no script e rode de novo. */
window.CIDADE_DO_AGRO = {"totalOficiais": 81, "posts": 39, "aparicoes": 83, "atualizadoEm": "2026-09-18"};

window.EMPRESAS = [
 {
  "id": "corteva",
  "nome": "Corteva Agriscience",
  "instagram": "cortevabr",
  "area": "Proteção de cultivos",
  "selo": "diamante",
  "post": "02",
  "carrossel": false,
  "frase": "Quem protege o cultivo, protege o futuro.",
  "texto": "A Corteva Agriscience entendeu que proteger o futuro do agronegócio gaúcho começa com estar presente onde ele está sendo construído.",
  "legenda": "A @cortevabr escolheu o Rio Grande do Sul não só como mercado, escolheu como casa. Aqui, onde o campo é cultura, identidade e sustento, a Corteva constrói junto com o produtor um legado que vai muito além da safra.\n\n📍 Cidade do Agro\n👉 Siga: @cidadedoagro_\n\n#CidadeDoAgro #Corteva #AgroGaúcho #MetadeSul #RioGrandeDoSul",
  "data": "2026-06-15",
  "codigo": "DZnKvTExCCE",
  "logo": "assets/logos/corteva.png",
  "arte": "assets/posts/post-02.jpg"
 },
 {
  "id": "fronteira-agro",
  "nome": "Fronteira Agro",
  "instagram": null,
  "area": "Revendas e insumos",
  "selo": "diamante",
  "post": "03",
  "carrossel": false,
  "frase": "A Fronteira Agro conhece esta terra porque faz parte dela.",
  "texto": "Com produtos e serviços, recebimento de grãos, e com presença de verdade. Parceria que faz a diferença.",
  "legenda": "30 anos não se resumem a números. Se resumem à presença. 🤝\n\nA Fronteira Agro está na Metade Sul do Rio Grande do Sul não como fornecedora — mas como parceira. Com insumos, assistência técnica e o compromisso de quem escolheu ficar ao lado do produtor rural, safra após safra.\n\nQuem conhece a terra, sabe como cuidar dela.\n\n📍 Cidade do Agro\n👉 Siga: @cidadedoagro_\n\n#CidadeDoAgro #FronteiraAgro #AgroGaúcho #MetadeSul #AssistênciaTécnica",
  "data": "2026-06-16",
  "codigo": "DZpPFtaRUi1",
  "logo": "assets/logos/fronteira-agro.png",
  "arte": "assets/posts/post-03.jpg"
 },
 {
  "id": "bioagreen",
  "nome": "Bioagreen",
  "instagram": "bioagreenagrociencia",
  "area": "Biológicos",
  "selo": "diamante",
  "post": "04",
  "carrossel": false,
  "frase": "Uma empresa gaúcha, em casa, construindo legado.",
  "texto": "Nosso compromisso é com a agricultura, testando e aperfeiçoando constantemente nosso portfólio entregando para o produtor as melhores soluções.",
  "legenda": "Nasceu aqui. Cresceu aqui. E segue inovando aqui. 🧬🌾\n\nA @bioagreenagrociencia é prova de que ciência e campo andam juntos quando a empresa entende de onde vem. Com soluções biológicas desenvolvidas para a realidade do produtor gaúcho, a Bioagreen não apenas entrega tecnologia, ela entrega pertencimento.\n\nPorque quem é daqui, sabe o que o campo precisa.\n\n📍 Cidade do Agro\n👉 Siga: @cidadedoagro_\n\n#CidadeDoAgro #BiológicosNoAgro #AgroGaúcho #InovaçãoNoCampo MetadeSul",
  "data": "2026-06-24",
  "codigo": "DZsPhcXxs5x",
  "logo": "assets/logos/bioagreen.png",
  "arte": "assets/posts/post-04.jpg"
 },
 {
  "id": "nachurs",
  "nome": "Nachurs",
  "instagram": null,
  "area": "Nutrição de cultivos",
  "selo": "diamante",
  "post": "05",
  "carrossel": false,
  "frase": "Uma empresa que não apenas entende de nutrição de cultivos, ela ajudou a inventar esse conceito.",
  "texto": "Tecnologia de nutrição de precisão com endereço fixo na Metade Sul do Rio Grande do Sul.",
  "legenda": "\"Uma empresa que não apenas entende de nutrição de cultivos, ela ajudou a inventar esse conceito.\"\n\nPioneira em fertilizantes líquidos, a marca que ajudou a escrever o manual da nutrição de cultivos tem endereço fixo na Metade Sul do Rio Grande do Sul — e segue entregando o que sempre entregou: ciência aplicada onde o produtor mais precisa.\n\nNão é novidade. É tradição com tecnologia. 🌱\n\n📍 Cidade do Agro\n👉 Siga: @cidadedoagro_\n\n#CidadeDoAgro #Nachurs #NutriçãoDePrecisão #FertilizantesLíquidos #AgroGaúcho",
  "data": "2026-06-24",
  "codigo": "DZuemMExoWE",
  "logo": "assets/logos/nachurs.png",
  "arte": "assets/posts/post-05.jpg"
 },
 {
  "id": "planfer",
  "nome": "Planfer",
  "instagram": null,
  "area": "Revendas e insumos",
  "selo": "diamante",
  "post": "06",
  "carrossel": false,
  "frase": "Uma empresa que não apenas conhece o produtor gaúcho. Ela caminha ao lado dele, safra após safra.",
  "texto": "A Planfer atende mais de 20 municípios em toda região sul do Rio Grande do Sul, sendo uma aliada do produtor rural, do plantio ao pós-colheita.",
  "legenda": "🌾 PLANFER \n\"Uma empresa que não apenas conhece o produtor gaúcho. Ela caminha ao lado dele, safra após safra.\"\n\nNão basta conhecer o campo. É preciso estar nele. 👣🌿\n\nA Planfer está presente em mais de 20 municípios da região sul do Rio Grande do Sul levando insumos, assistência e a certeza de que o produtor nunca está sozinho — do plantio ao pós-colheita.\n\nPorque parceria de verdade não termina na venda. Ela começa nela.\n\n📍 Cidade do Agro\n👉 Siga: @cidadedoagro_\n\n#CidadeDoAgro #Planfer #AgroGaúcho #MetadeSul #InsumoAgricola",
  "data": "2026-06-19",
  "codigo": "DZxT4axRyGe",
  "logo": "assets/logos/planfer.png",
  "arte": "assets/posts/post-06.jpg"
 },
 {
  "id": "elo-agronegocios",
  "nome": "Elo Agronegócios",
  "instagram": null,
  "area": "Revendas e insumos",
  "selo": "diamante",
  "post": "07",
  "carrossel": false,
  "frase": "Elo Agronegócios é especializada em insumos para as culturas que definem a Metade Sul: arroz irrigado, soja, milho e pastagens.",
  "texto": "Uma empresa que não só conhece o campo daqui — ela faz parte dele.",
  "legenda": "ELO AGRONEGÓCIOS\n\n\"Uma empresa que não só conhece o campo daqui, ela faz parte dele.\"\n\nArroz, soja, milho, pastagens. As culturas que definem a Metade Sul têm um parceiro à altura. 🌾\n\nA Elo Agronegócios é especializada nas culturas que moldam a identidade do campo gaúcho — e faz isso com a profundidade de quem não apenas atende o produtor, mas vive na mesma terra que ele.\n\nElo. O nome já diz tudo: conexão, confiança, campo. 🤝\n\n📍 Cidade do Agro\n👉 Siga: @cidadedoagro_\n\n#CidadeDoAgro #EloAgronegócios #AgroGaúcho #MetadeSul #ArrozIrrigado",
  "data": "2026-06-24",
  "codigo": "DZzvxDExsYP",
  "logo": "assets/logos/elo-agronegocios.png",
  "arte": "assets/posts/post-07.jpg"
 },
 {
  "id": "agrofel",
  "nome": "Agrofel",
  "instagram": null,
  "area": "Revendas e insumos",
  "selo": "diamante",
  "post": "08",
  "carrossel": false,
  "frase": "Com você em todo o tempo e agora, também aqui. 🌾",
  "texto": "Do plantio à colheita, em mais de 50 unidades espalhadas pelo Rio Grande do Sul, construindo confiança.",
  "legenda": "Quase cinco décadas. Mais de 50 unidades. Uma só missão. 🌾\n\nA Agrofel construiu algo que vai muito além de uma rede de lojas no Rio Grande do Sul: construiu confiança. Do plantio à colheita, do produtor à família, a Agrofel é aquela presença que o campo gaúcho já conhece.\n\nPorque quem cuida do campo, cuida de tudo. 💚\n\n📍 Cidade do Agro\n👉 Siga: @cidadedoagro_\n\n#CidadeDoAgro #Agrofel #AgroGaúcho #RioGrandeDoSul #InsumoAgricola",
  "data": "2026-06-21",
  "codigo": "DZ2Mt78R2Ns",
  "logo": "assets/logos/agrofel.png",
  "arte": "assets/posts/post-08.jpg"
 },
 {
  "id": "real-agro",
  "nome": "Real Agro",
  "instagram": null,
  "area": "Consultoria e gestão",
  "selo": "ouro",
  "post": "09",
  "carrossel": false,
  "frase": "Consultoria e assessoria agropecuária em Pelotas e região, sempre ao lado do produtor, do planejamento à execução.",
  "texto": "Atua em crédito rural, consultoria financeira, seguro agrícola e assistência técnica.",
  "legenda": "🌾 Real Agro \n\nReferência em consultoria e assessoria agropecuária em Pelotas e região, a Real Agro atua em crédito rural, consultoria financeira, seguro agrícola e assistência técnica — sempre ao lado do produtor, do planejamento à execução.\nUma empresa que constrói relação de confiança com o produtor, se conecta com um ecossistema que nasceu com a mesma vocação: presença contínua, e não pontual. \n📍 Cidade do Agro\n👉 Siga: @cidadedoagro_\n\n#CidadeDoAgro #Agrofel #AgroGaúcho #RioGrandeDoSul #InsumoAgricola",
  "data": "2026-06-22",
  "codigo": "DZ5hnGlR0dM",
  "logo": "assets/logos/real-agro.png",
  "arte": "assets/posts/post-09.jpg"
 },
 {
  "id": "fmc",
  "nome": "FMC",
  "instagram": null,
  "area": "Proteção de cultivos",
  "selo": "ouro",
  "post": "10",
  "carrossel": false,
  "frase": "Empresa de ciências agrícolas, ligada à história do agronegócio, comprometida com as necessidades do campo.",
  "texto": "Soluções para proteção de cultivos (herbicidas, inseticidas, fungicidas, biológicos e tratamento de sementes) em soja, milho, arroz e trigo.",
  "legenda": "FMC \nMultinacional de referência em soluções para proteção de cultivos herbicidas, inseticidas, fungicidas, biológicos e tratamento de sementes, a FMC atua junto a diversas culturas estratégicas, como soja, milho, arroz e trigo. 📍 Cidade do Agro\n👉 Siga: @cidadedoagro_\n\n#CidadeDoAgro #Agrofel #AgroGaúcho #RioGrandeDoSul #InsumoAgricola",
  "data": "2026-06-24",
  "codigo": "DZ98Tj0RWhz",
  "logo": "assets/logos/fmc.png",
  "arte": "assets/posts/post-10.jpg"
 },
 {
  "id": "advanta",
  "nome": "Advanta",
  "instagram": null,
  "area": "Sementes",
  "selo": "ouro",
  "post": "11",
  "carrossel": false,
  "frase": "A Advanta é uma empresa global de soluções agrícolas com um portfólio de sementes híbridas avançadas em milho, sorgo, canola, girassol e outros cultivos.",
  "texto": "Mais de 50 anos de experiência em melhoramento genético de plantas.",
  "legenda": "A Advanta é uma empresa global de soluções agrícolas com um portfólio de sementes híbridas avançadas em milho, sorgo, canola, girassol e outros cultivos, com mais de 50 anos de experiência em melhoramento genético de plantas. Nossas tecnologias, como o Igrowth em sorgo, entregam excelentes resultados em diferentes as condições de cultivo. 📍 Cidade do Agro\n👉 Siga: @cidadedoagro_\n\n#CidadeDoAgro #AgroGaúcho #RioGrandeDoSul #insumoagricola",
  "data": "2026-06-25",
  "codigo": "DaA8D0JR-y6",
  "logo": "assets/logos/advanta.png",
  "arte": "assets/posts/post-11.jpg"
 },
 {
  "id": "3tentos",
  "nome": "3tentos",
  "instagram": null,
  "area": "Revendas e insumos",
  "selo": "ouro",
  "post": "12",
  "carrossel": false,
  "frase": "Referência do agronegócio gaúcho, atuando do planejamento à comercialização, da assistência técnica até os biocombustíveis.",
  "texto": "Sementes, fertilizantes, defensivos, grãos e biocombustível — e agora soma forças com um projeto que nasceu para estar perto do produtor o ano inteiro.",
  "legenda": "Referência do agronegócio gaúcho, a 3tentos atua do planejamento à comercialização, assistência técnica, sementes, fertilizantes, defensivos, grãos e biocombustível , e agora soma forças com um projeto que nasceu com uma missão clara: estar perto do produtor o ano inteiro.\nUma empresa que já é sinônimo de presença constante junto ao produtor rural. 📍 Cidade do Agro\n👉 Siga: @cidadedoagro_\n\n#CidadeDoAgro #Agrofel #AgroGaúcho #RioGrandeDoSul #InsumoAgricola",
  "data": "2026-06-26",
  "codigo": "DaDEvhVx2e7",
  "logo": "assets/logos/3tentos.png",
  "arte": "assets/posts/post-12.jpg"
 },
 {
  "id": "yara",
  "nome": "Yara",
  "instagram": null,
  "area": "Nutrição de cultivos",
  "selo": "ouro",
  "post": "13",
  "carrossel": false,
  "frase": "Referência mundial em nutrição de plantas, a Yara atua em fertilizantes premium, bioinsumos, foliares e programas nutricionais para mais de 20 culturas.",
  "texto": "Do HF à soja, do milho ao trigo, sempre com foco em produtividade e sustentabilidade.",
  "legenda": "Uma empresa que carrega a missão de alimentar o mundo cuidando do planeta se conecta com um ecossistema que nasceu com a mesma vocação: presença contínua, e não pontual. 📍 Cidade do Agro\n👉 Siga: @cidadedoagro_\n\n#CidadeDoAgro #AgroGaúcho #RioGrandeDoSul #InsumoAgricola #produçãorural",
  "data": "2026-06-30",
  "codigo": "DaOkzi8RUuA",
  "logo": "assets/logos/yara.png",
  "arte": "assets/posts/post-13.jpg"
 },
 {
  "id": "plantecnica",
  "nome": "Plantécnica",
  "instagram": null,
  "area": "Revendas e insumos",
  "selo": "ouro",
  "post": "14",
  "carrossel": false,
  "frase": "Desde 2003 no mercado de insumos agrícolas, a Plantécnica é referência em Pelotas e região.",
  "texto": "Fertilizantes, sementes, insumos e originação de grãos, com proximidade e atendimento técnico personalizado.",
  "legenda": "“Desde 2003 no mercado de insumos agrícolas, a Plantécnica é referência em Pelotas e região, atuando desde fertilizantes, sementes, insumos até a originação de grãos, sempre com proximidade e atendimento técnico personalizado.\n\nJuntos impulsionamos o futuro do agro!” \n \n📍 Cidade do Agro\n👉 Siga: @cidadedoagro_\n\n#CidadeDoAgro #AgroGaúcho #RioGrandeDoSul #InsumoAgricola #ProduçãoRural",
  "data": "2026-07-01",
  "codigo": "DaQ6-zHRGNL",
  "logo": "assets/logos/plantecnica.png",
  "arte": "assets/posts/post-14.jpg"
 },
 {
  "id": "basf",
  "nome": "BASF",
  "instagram": null,
  "area": "Proteção de cultivos",
  "selo": "diamante",
  "post": "15",
  "carrossel": false,
  "frase": "Juntos pelo seu legado. Esse é o compromisso que a BASF assume com cada agricultor, em cada safra, em cada nova geração.",
  "texto": "Trazendo ciência de ponta para o agronegócio!",
  "legenda": "Juntos pelo seu legado. Esse é o compromisso que a BASF assume com cada agricultor, em cada safra, em cada nova geração  e é exatamente esse espírito que ela traz para a Cidade do Agro.\n\n📍 Cidade do Agro\n👉 Siga: @cidadedoagro_\n\n#CidadeDoAgro #AgroGaúcho #RioGrandeDoSul #InsumoAgricola #ProduçãoRural",
  "data": "2026-07-03",
  "codigo": "DaVG2P2hSE6",
  "logo": "assets/logos/basf.png",
  "arte": "assets/posts/post-15.jpg"
 },
 {
  "id": "fida",
  "nome": "FIDA",
  "instagram": "fidaoficial",
  "area": "A confirmar",
  "selo": "prata",
  "post": "16.1",
  "carrossel": true,
  "frase": null,
  "texto": "Marca apresentada no carrossel “Marcas que apoiam a Cidade do Agro”.",
  "legenda": "Marcas que apoiam Cidade do Agro\n\n@fidaoficial \n\n@mosaicnobrasil \n\n@digitagro \n\n@rovensanextbrasil\n\n@bioma.agro \n\n#fida #mosaic #digitagro #rovenza #bioma",
  "data": "2026-07-08",
  "codigo": "Dac6L7sEQl_",
  "logo": "assets/logos/fida.png",
  "arte": "assets/posts/post-16-1.jpg"
 },
 {
  "id": "mosaic",
  "nome": "Mosaic",
  "instagram": "mosaicnobrasil",
  "area": "Nutrição de cultivos",
  "selo": "prata",
  "post": "16.2",
  "carrossel": true,
  "frase": null,
  "texto": "Marca apresentada no carrossel “Marcas que apoiam a Cidade do Agro”.",
  "legenda": "Marcas que apoiam Cidade do Agro\n\n@fidaoficial \n\n@mosaicnobrasil \n\n@digitagro \n\n@rovensanextbrasil\n\n@bioma.agro \n\n#fida #mosaic #digitagro #rovenza #bioma",
  "data": "2026-07-08",
  "codigo": "Dac6L7sEQl_",
  "logo": "assets/logos/mosaic.png",
  "arte": "assets/posts/post-16-2.jpg"
 },
 {
  "id": "digitagro",
  "nome": "Digitagro",
  "instagram": "digitagro",
  "area": "A confirmar",
  "selo": "prata",
  "post": "16.3",
  "carrossel": true,
  "frase": null,
  "texto": "Marca apresentada no carrossel “Marcas que apoiam a Cidade do Agro”.",
  "legenda": "Marcas que apoiam Cidade do Agro\n\n@fidaoficial \n\n@mosaicnobrasil \n\n@digitagro \n\n@rovensanextbrasil\n\n@bioma.agro \n\n#fida #mosaic #digitagro #rovenza #bioma",
  "data": "2026-07-08",
  "codigo": "Dac6L7sEQl_",
  "logo": "assets/logos/digitagro.png",
  "arte": "assets/posts/post-16-3.jpg"
 },
 {
  "id": "rovensa-next",
  "nome": "Rovensa Next",
  "instagram": "rovensanextbrasil",
  "area": "Biológicos",
  "selo": "prata",
  "post": "16.4",
  "carrossel": true,
  "frase": null,
  "texto": "Marca apresentada no carrossel “Marcas que apoiam a Cidade do Agro”.",
  "legenda": "Marcas que apoiam Cidade do Agro\n\n@fidaoficial \n\n@mosaicnobrasil \n\n@digitagro \n\n@rovensanextbrasil\n\n@bioma.agro \n\n#fida #mosaic #digitagro #rovenza #bioma",
  "data": "2026-07-08",
  "codigo": "Dac6L7sEQl_",
  "logo": "assets/logos/rovensa-next.png",
  "arte": "assets/posts/post-16-4.jpg"
 },
 {
  "id": "bioma",
  "nome": "Bioma",
  "instagram": "bioma.agro",
  "area": "Biológicos",
  "selo": "prata",
  "post": "16.5",
  "carrossel": true,
  "frase": null,
  "texto": "Marca apresentada no carrossel “Marcas que apoiam a Cidade do Agro”.",
  "legenda": "Marcas que apoiam Cidade do Agro\n\n@fidaoficial \n\n@mosaicnobrasil \n\n@digitagro \n\n@rovensanextbrasil\n\n@bioma.agro \n\n#fida #mosaic #digitagro #rovenza #bioma",
  "data": "2026-07-08",
  "codigo": "Dac6L7sEQl_",
  "logo": "assets/logos/bioma.png",
  "arte": "assets/posts/post-16-5.jpg"
 },
 {
  "id": "bayer",
  "nome": "Bayer",
  "instagram": "agrobayerbrasil",
  "area": "Proteção de cultivos",
  "selo": "prata",
  "post": "17.1",
  "carrossel": true,
  "frase": null,
  "texto": "Marca apresentada no carrossel “Marcas que apoiam a Cidade do Agro”.",
  "legenda": "Marcas que apoiam Cidade do Agro.\n\n@agrobayerbrasil \n\n@produzainsumos\n\n@fund.fdms\n\nAyres corretora de cereais \n\n@invernadaagroinsumos\n\n#bayer #produza #fundacao #ayrescorretora #invernada",
  "data": "2026-07-08",
  "codigo": "DadAK9KkbXo",
  "logo": "assets/logos/bayer.png",
  "arte": "assets/posts/post-17-1.jpg"
 },
 {
  "id": "produza",
  "nome": "Produza",
  "instagram": "produzainsumos",
  "area": "Revendas e insumos",
  "selo": "prata",
  "post": "17.2",
  "carrossel": true,
  "frase": null,
  "texto": "Marca apresentada no carrossel “Marcas que apoiam a Cidade do Agro”.",
  "legenda": "Marcas que apoiam Cidade do Agro.\n\n@agrobayerbrasil \n\n@produzainsumos\n\n@fund.fdms\n\nAyres corretora de cereais \n\n@invernadaagroinsumos\n\n#bayer #produza #fundacao #ayrescorretora #invernada",
  "data": "2026-07-08",
  "codigo": "DadAK9KkbXo",
  "logo": "assets/logos/produza.png",
  "arte": "assets/posts/post-17-2.jpg"
 },
 {
  "id": "fundacao-fdms",
  "nome": "Fundação Delfim Mendes Silveira",
  "instagram": "fund.fdms",
  "area": "Instituições e entidades",
  "selo": "prata",
  "post": "17.3",
  "carrossel": true,
  "frase": null,
  "texto": "Marca apresentada no carrossel “Marcas que apoiam a Cidade do Agro”.",
  "legenda": "Marcas que apoiam Cidade do Agro.\n\n@agrobayerbrasil \n\n@produzainsumos\n\n@fund.fdms\n\nAyres corretora de cereais \n\n@invernadaagroinsumos\n\n#bayer #produza #fundacao #ayrescorretora #invernada",
  "data": "2026-07-08",
  "codigo": "DadAK9KkbXo",
  "logo": "assets/logos/fundacao-fdms.png",
  "arte": "assets/posts/post-17-3.jpg"
 },
 {
  "id": "ayres",
  "nome": "Ayres Corretora de Cereais",
  "instagram": null,
  "area": "Comercialização de grãos",
  "selo": "prata",
  "post": "17.4",
  "carrossel": true,
  "frase": null,
  "texto": "Marca apresentada no carrossel “Marcas que apoiam a Cidade do Agro”.",
  "legenda": "Marcas que apoiam Cidade do Agro.\n\n@agrobayerbrasil \n\n@produzainsumos\n\n@fund.fdms\n\nAyres corretora de cereais \n\n@invernadaagroinsumos\n\n#bayer #produza #fundacao #ayrescorretora #invernada",
  "data": "2026-07-08",
  "codigo": "DadAK9KkbXo",
  "logo": "assets/logos/ayres.png",
  "arte": "assets/posts/post-17-4.jpg"
 },
 {
  "id": "invernada",
  "nome": "Invernada Agroinsumos",
  "instagram": "invernadaagroinsumos",
  "area": "Revendas e insumos",
  "selo": "prata",
  "post": "17.5",
  "carrossel": true,
  "frase": null,
  "texto": "Marca apresentada no carrossel “Marcas que apoiam a Cidade do Agro”.",
  "legenda": "Marcas que apoiam Cidade do Agro.\n\n@agrobayerbrasil \n\n@produzainsumos\n\n@fund.fdms\n\nAyres corretora de cereais \n\n@invernadaagroinsumos\n\n#bayer #produza #fundacao #ayrescorretora #invernada",
  "data": "2026-07-08",
  "codigo": "DadAK9KkbXo",
  "logo": "assets/logos/invernada.png",
  "arte": "assets/posts/post-17-5.jpg"
 },
 {
  "id": "vitalforce",
  "nome": "Vitalforce",
  "instagram": "vitalforcebrasil",
  "area": "A confirmar",
  "selo": "prata",
  "post": "18.1",
  "carrossel": true,
  "frase": null,
  "texto": "Marca apresentada no carrossel “Marcas que apoiam a Cidade do Agro”.",
  "legenda": "Marcas que apoiam a Cidade do Agro\n\n@vitalforcebrasil\n\n@terradotearth\n\n@jwgeologia\n\n@corretora.arrozsul\n\n@tritaxconsultoria\n\n#vitalforce #terradot #jwgeologia #arrozsul #tritax",
  "data": "2026-07-08",
  "codigo": "DafdxKsEcBc",
  "logo": "assets/logos/vitalforce.png",
  "arte": "assets/posts/post-18-1.jpg"
 },
 {
  "id": "terradot",
  "nome": "Terradot",
  "instagram": "terradotearth",
  "area": "A confirmar",
  "selo": "prata",
  "post": "18.2",
  "carrossel": true,
  "frase": null,
  "texto": "Marca apresentada no carrossel “Marcas que apoiam a Cidade do Agro”.",
  "legenda": "Marcas que apoiam a Cidade do Agro\n\n@vitalforcebrasil\n\n@terradotearth\n\n@jwgeologia\n\n@corretora.arrozsul\n\n@tritaxconsultoria\n\n#vitalforce #terradot #jwgeologia #arrozsul #tritax",
  "data": "2026-07-08",
  "codigo": "DafdxKsEcBc",
  "logo": "assets/logos/terradot.png",
  "arte": "assets/posts/post-18-2.jpg"
 },
 {
  "id": "jw-geologia",
  "nome": "JW Geologia e Engenharia",
  "instagram": "jwgeologia",
  "area": "Serviços técnicos",
  "selo": "prata",
  "post": "18.3",
  "carrossel": true,
  "frase": null,
  "texto": "Marca apresentada no carrossel “Marcas que apoiam a Cidade do Agro”.",
  "legenda": "Marcas que apoiam a Cidade do Agro\n\n@vitalforcebrasil\n\n@terradotearth\n\n@jwgeologia\n\n@corretora.arrozsul\n\n@tritaxconsultoria\n\n#vitalforce #terradot #jwgeologia #arrozsul #tritax",
  "data": "2026-07-08",
  "codigo": "DafdxKsEcBc",
  "logo": "assets/logos/jw-geologia.png",
  "arte": "assets/posts/post-18-3.jpg"
 },
 {
  "id": "arroz-sul",
  "nome": "Arroz Sul Corretora",
  "instagram": "corretora.arrozsul",
  "area": "Comercialização de grãos",
  "selo": "prata",
  "post": "18.4",
  "carrossel": true,
  "frase": null,
  "texto": "Marca apresentada no carrossel “Marcas que apoiam a Cidade do Agro”.",
  "legenda": "Marcas que apoiam a Cidade do Agro\n\n@vitalforcebrasil\n\n@terradotearth\n\n@jwgeologia\n\n@corretora.arrozsul\n\n@tritaxconsultoria\n\n#vitalforce #terradot #jwgeologia #arrozsul #tritax",
  "data": "2026-07-08",
  "codigo": "DafdxKsEcBc",
  "logo": "assets/logos/arroz-sul.png",
  "arte": "assets/posts/post-18-4.jpg"
 },
 {
  "id": "tritax",
  "nome": "Tritax Consultoria",
  "instagram": "tritaxconsultoria",
  "area": "Consultoria e gestão",
  "selo": "prata",
  "post": "18.5",
  "carrossel": true,
  "frase": null,
  "texto": "Marca apresentada no carrossel “Marcas que apoiam a Cidade do Agro”.",
  "legenda": "Marcas que apoiam a Cidade do Agro\n\n@vitalforcebrasil\n\n@terradotearth\n\n@jwgeologia\n\n@corretora.arrozsul\n\n@tritaxconsultoria\n\n#vitalforce #terradot #jwgeologia #arrozsul #tritax",
  "data": "2026-07-08",
  "codigo": "DafdxKsEcBc",
  "logo": "assets/logos/tritax.png",
  "arte": "assets/posts/post-18-5.jpg"
 },
 {
  "id": "coragon",
  "nome": "Coragon Agropecuária",
  "instagram": "coragon_agropecuaria",
  "area": "Produtores rurais",
  "selo": "bronze",
  "post": "19.1",
  "carrossel": true,
  "frase": null,
  "texto": "Marca apresentada no carrossel “Marcas que apoiam a Cidade do Agro”.",
  "legenda": "Marcas que apoiam Cidade do Agro \n\n@coragon_agropecuaria\n\n@akvoengenharia\n\n@bsradvogadosoficial\n\n@lider.projetos\n\n#connectere #coragon #akvo #bsr #líder",
  "data": "2026-08-24",
  "codigo": "DafqiOPkYy2",
  "logo": "assets/logos/coragon.png",
  "arte": "assets/posts/post-19-1.jpg",
  "tambem": [
   "22.1"
  ]
 },
 {
  "id": "akvo",
  "nome": "Akvo Engenharia",
  "instagram": "akvoengenharia",
  "area": "Serviços técnicos",
  "selo": "bronze",
  "post": "19.2",
  "carrossel": true,
  "frase": null,
  "texto": "Marca apresentada no carrossel “Marcas que apoiam a Cidade do Agro”.",
  "legenda": "Marcas que apoiam Cidade do Agro \n\n@coragon_agropecuaria\n\n@akvoengenharia\n\n@bsradvogadosoficial\n\n@lider.projetos\n\n#connectere #coragon #akvo #bsr #líder",
  "data": "2026-08-24",
  "codigo": "DafqiOPkYy2",
  "logo": "assets/logos/akvo.png",
  "arte": "assets/posts/post-19-2.jpg"
 },
 {
  "id": "bsr",
  "nome": "BSR Advogados",
  "instagram": "bsradvogadosoficial",
  "area": "Jurídico",
  "selo": "bronze",
  "post": "19.3",
  "carrossel": true,
  "frase": null,
  "texto": "Marca apresentada no carrossel “Marcas que apoiam a Cidade do Agro”.",
  "legenda": "Marcas que apoiam Cidade do Agro \n\n@coragon_agropecuaria\n\n@akvoengenharia\n\n@bsradvogadosoficial\n\n@lider.projetos\n\n#connectere #coragon #akvo #bsr #líder",
  "data": "2026-08-24",
  "codigo": "DafqiOPkYy2",
  "logo": "assets/logos/bsr.png",
  "arte": "assets/posts/post-19-3.jpg"
 },
 {
  "id": "lider-projetos",
  "nome": "Líder Projetos",
  "instagram": "lider.projetos",
  "area": "A confirmar",
  "selo": "bronze",
  "post": "19.4",
  "carrossel": true,
  "frase": null,
  "texto": "Marca apresentada no carrossel “Marcas que apoiam a Cidade do Agro”.",
  "legenda": "Marcas que apoiam Cidade do Agro \n\n@coragon_agropecuaria\n\n@akvoengenharia\n\n@bsradvogadosoficial\n\n@lider.projetos\n\n#connectere #coragon #akvo #bsr #líder",
  "data": "2026-08-24",
  "codigo": "DafqiOPkYy2",
  "logo": "assets/logos/lider-projetos.png",
  "arte": "assets/posts/post-19-4.jpg"
 },
 {
  "id": "porteira-adentro",
  "nome": "Porteira Adentro Consultoria",
  "instagram": "porteiraadentroconsultoria",
  "area": "Consultoria e gestão",
  "selo": "bronze",
  "post": "20.1",
  "carrossel": true,
  "frase": null,
  "texto": "Marca apresentada no carrossel “Marcas que apoiam a Cidade do Agro”.",
  "legenda": "Marcas que apoiam a Cidade do Agro\n\n@porteiraadentroconsultoria\n\n@fortegraos \n\n@sementessimao \n\n@cereagrocorretora \n\n@almeidaeraymundo \n\n#porteiraadentro #fortrgraos #sementesimao #cereagro #almeida&raymundo",
  "data": "2026-07-08",
  "codigo": "DagKmiFkeQg",
  "logo": "assets/logos/porteira-adentro.png",
  "arte": "assets/posts/post-20-1.jpg"
 },
 {
  "id": "forte-graos",
  "nome": "Forte Grãos",
  "instagram": "fortegraos",
  "area": "Comercialização de grãos",
  "selo": "bronze",
  "post": "20.2",
  "carrossel": true,
  "frase": null,
  "texto": "Marca apresentada no carrossel “Marcas que apoiam a Cidade do Agro”.",
  "legenda": "Marcas que apoiam a Cidade do Agro\n\n@porteiraadentroconsultoria\n\n@fortegraos \n\n@sementessimao \n\n@cereagrocorretora \n\n@almeidaeraymundo \n\n#porteiraadentro #fortrgraos #sementesimao #cereagro #almeida&raymundo",
  "data": "2026-07-08",
  "codigo": "DagKmiFkeQg",
  "logo": "assets/logos/forte-graos.png",
  "arte": "assets/posts/post-20-2.jpg"
 },
 {
  "id": "sementes-simao",
  "nome": "Sementes Simão",
  "instagram": "sementessimao",
  "area": "Sementes",
  "selo": "bronze",
  "post": "20.3",
  "carrossel": true,
  "frase": null,
  "texto": "Marca apresentada no carrossel “Marcas que apoiam a Cidade do Agro”.",
  "legenda": "Marcas que apoiam a Cidade do Agro\n\n@porteiraadentroconsultoria\n\n@fortegraos \n\n@sementessimao \n\n@cereagrocorretora \n\n@almeidaeraymundo \n\n#porteiraadentro #fortrgraos #sementesimao #cereagro #almeida&raymundo",
  "data": "2026-07-08",
  "codigo": "DagKmiFkeQg",
  "logo": "assets/logos/sementes-simao.png",
  "arte": "assets/posts/post-20-3.jpg"
 },
 {
  "id": "cereagro",
  "nome": "Cereagro Corretora de Cereais",
  "instagram": "cereagrocorretora",
  "area": "Comercialização de grãos",
  "selo": "bronze",
  "post": "20.4",
  "carrossel": true,
  "frase": null,
  "texto": "Marca apresentada no carrossel “Marcas que apoiam a Cidade do Agro”.",
  "legenda": "Marcas que apoiam a Cidade do Agro\n\n@porteiraadentroconsultoria\n\n@fortegraos \n\n@sementessimao \n\n@cereagrocorretora \n\n@almeidaeraymundo \n\n#porteiraadentro #fortrgraos #sementesimao #cereagro #almeida&raymundo",
  "data": "2026-07-08",
  "codigo": "DagKmiFkeQg",
  "logo": "assets/logos/cereagro.png",
  "arte": "assets/posts/post-20-4.jpg"
 },
 {
  "id": "almeida-raymundo",
  "nome": "Almeida & Raymundo Advogados",
  "instagram": "almeidaeraymundo",
  "area": "Jurídico",
  "selo": "bronze",
  "post": "20.5",
  "carrossel": true,
  "frase": null,
  "texto": "Marca apresentada no carrossel “Marcas que apoiam a Cidade do Agro”.",
  "legenda": "Marcas que apoiam a Cidade do Agro\n\n@porteiraadentroconsultoria\n\n@fortegraos \n\n@sementessimao \n\n@cereagrocorretora \n\n@almeidaeraymundo \n\n#porteiraadentro #fortrgraos #sementesimao #cereagro #almeida&raymundo",
  "data": "2026-07-08",
  "codigo": "DagKmiFkeQg",
  "logo": "assets/logos/almeida-raymundo.png",
  "arte": "assets/posts/post-20-5.jpg"
 },
 {
  "id": "fcosta",
  "nome": "F. Costa Sementes",
  "instagram": "fcosta.sementes",
  "area": "Sementes",
  "selo": "bronze",
  "post": "21.1",
  "carrossel": true,
  "frase": null,
  "texto": "Marca apresentada no carrossel “Marcas que apoiam a Cidade do Agro”.",
  "legenda": "Marcas que apoiam a Cidade do Agro \n\n@fcosta.sementes\n\n@adama_brasil \n\n@farmboxapp\n\n@allianzadobrasil\n\n@ccmautomacao\n\n#fcostasementes #adama #farmbox #allianzza #ccmautomacao",
  "data": "2026-07-08",
  "codigo": "DagPiDiGS2M",
  "logo": "assets/logos/fcosta.png",
  "arte": "assets/posts/post-21-1.jpg"
 },
 {
  "id": "adama",
  "nome": "ADAMA",
  "instagram": "adama_brasil",
  "area": "Proteção de cultivos",
  "selo": "bronze",
  "post": "21.2",
  "carrossel": true,
  "frase": null,
  "texto": "Marca apresentada no carrossel “Marcas que apoiam a Cidade do Agro”.",
  "legenda": "Marcas que apoiam a Cidade do Agro \n\n@fcosta.sementes\n\n@adama_brasil \n\n@farmboxapp\n\n@allianzadobrasil\n\n@ccmautomacao\n\n#fcostasementes #adama #farmbox #allianzza #ccmautomacao",
  "data": "2026-07-08",
  "codigo": "DagPiDiGS2M",
  "logo": "assets/logos/adama.png",
  "arte": "assets/posts/post-21-2.jpg"
 },
 {
  "id": "farmbox",
  "nome": "Farmbox",
  "instagram": "farmboxapp",
  "area": "Tecnologia e automação",
  "selo": "bronze",
  "post": "21.3",
  "carrossel": true,
  "frase": null,
  "texto": "Marca apresentada no carrossel “Marcas que apoiam a Cidade do Agro”.",
  "legenda": "Marcas que apoiam a Cidade do Agro \n\n@fcosta.sementes\n\n@adama_brasil \n\n@farmboxapp\n\n@allianzadobrasil\n\n@ccmautomacao\n\n#fcostasementes #adama #farmbox #allianzza #ccmautomacao",
  "data": "2026-07-08",
  "codigo": "DagPiDiGS2M",
  "logo": "assets/logos/farmbox.png",
  "arte": "assets/posts/post-21-3.jpg"
 },
 {
  "id": "allianza",
  "nome": "Allianza",
  "instagram": "allianzadobrasil",
  "area": "A confirmar",
  "selo": "bronze",
  "post": "21.4",
  "carrossel": true,
  "frase": null,
  "texto": "Marca apresentada no carrossel “Marcas que apoiam a Cidade do Agro”.",
  "legenda": "Marcas que apoiam a Cidade do Agro \n\n@fcosta.sementes\n\n@adama_brasil \n\n@farmboxapp\n\n@allianzadobrasil\n\n@ccmautomacao\n\n#fcostasementes #adama #farmbox #allianzza #ccmautomacao",
  "data": "2026-07-08",
  "codigo": "DagPiDiGS2M",
  "logo": "assets/logos/allianza.png",
  "arte": "assets/posts/post-21-4.jpg"
 },
 {
  "id": "ccm",
  "nome": "CCM Automação",
  "instagram": "ccmautomacao",
  "area": "Tecnologia e automação",
  "selo": "bronze",
  "post": "21.5",
  "carrossel": true,
  "frase": null,
  "texto": "Marca apresentada no carrossel “Marcas que apoiam a Cidade do Agro”.",
  "legenda": "Marcas que apoiam a Cidade do Agro \n\n@fcosta.sementes\n\n@adama_brasil \n\n@farmboxapp\n\n@allianzadobrasil\n\n@ccmautomacao\n\n#fcostasementes #adama #farmbox #allianzza #ccmautomacao",
  "data": "2026-07-08",
  "codigo": "DagPiDiGS2M",
  "logo": "assets/logos/ccm.png",
  "arte": "assets/posts/post-21-5.jpg"
 },
 {
  "id": "drakkar",
  "nome": "Drakkar Agricultura de Precisão",
  "instagram": "drakkarap",
  "area": "Tecnologia e automação",
  "selo": "bronze",
  "post": "22.2",
  "carrossel": true,
  "frase": null,
  "texto": "Marca apresentada no carrossel “Marcas que apoiam a Cidade do Agro”.",
  "legenda": "Marcas que apoiam a Cidade do Agro\n\n@coragon_agropecuaria\n\n@drakkarap\n \n@forquimicaagrociencia\n\n@mauromottaseguros\n\n@cropsteam\n\n#coragon #drakkar #forquimica #mauromottaseguros #cropsteam",
  "data": "2026-07-08",
  "codigo": "DaiVJDvgP5E",
  "logo": "assets/logos/drakkar.png",
  "arte": "assets/posts/post-22-2.jpg"
 },
 {
  "id": "forquimica",
  "nome": "Forquímica Agrociência",
  "instagram": "forquimicaagrociencia",
  "area": "A confirmar",
  "selo": "bronze",
  "post": "22.3",
  "carrossel": true,
  "frase": null,
  "texto": "Marca apresentada no carrossel “Marcas que apoiam a Cidade do Agro”.",
  "legenda": "Marcas que apoiam a Cidade do Agro\n\n@coragon_agropecuaria\n\n@drakkarap\n \n@forquimicaagrociencia\n\n@mauromottaseguros\n\n@cropsteam\n\n#coragon #drakkar #forquimica #mauromottaseguros #cropsteam",
  "data": "2026-07-08",
  "codigo": "DaiVJDvgP5E",
  "logo": "assets/logos/forquimica.png",
  "arte": "assets/posts/post-22-3.jpg"
 },
 {
  "id": "mauro-motta",
  "nome": "Mauro Motta Seguros",
  "instagram": "mauromottaseguros",
  "area": "Crédito, seguros e finanças",
  "selo": "bronze",
  "post": "22.4",
  "carrossel": true,
  "frase": null,
  "texto": "Marca apresentada no carrossel “Marcas que apoiam a Cidade do Agro”.",
  "legenda": "Marcas que apoiam a Cidade do Agro\n\n@coragon_agropecuaria\n\n@drakkarap\n \n@forquimicaagrociencia\n\n@mauromottaseguros\n\n@cropsteam\n\n#coragon #drakkar #forquimica #mauromottaseguros #cropsteam",
  "data": "2026-07-08",
  "codigo": "DaiVJDvgP5E",
  "logo": "assets/logos/mauro-motta.png",
  "arte": "assets/posts/post-22-4.jpg"
 },
 {
  "id": "crops-team",
  "nome": "Crops Team",
  "instagram": "cropsteam",
  "area": "Consultoria e gestão",
  "selo": "bronze",
  "post": "22.5",
  "carrossel": true,
  "frase": null,
  "texto": "Marca apresentada no carrossel “Marcas que apoiam a Cidade do Agro”.",
  "legenda": "Marcas que apoiam a Cidade do Agro\n\n@coragon_agropecuaria\n\n@drakkarap\n \n@forquimicaagrociencia\n\n@mauromottaseguros\n\n@cropsteam\n\n#coragon #drakkar #forquimica #mauromottaseguros #cropsteam",
  "data": "2026-07-08",
  "codigo": "DaiVJDvgP5E",
  "logo": "assets/logos/crops-team.png",
  "arte": "assets/posts/post-22-5.jpg",
  "tambem": [
   "24.4"
  ]
 },
 {
  "id": "cropchem",
  "nome": "CropChem",
  "instagram": "cropchembrasil",
  "area": "Proteção de cultivos",
  "selo": "prata",
  "post": "23.1",
  "carrossel": true,
  "frase": null,
  "texto": "Marca apresentada no carrossel “Marcas que apoiam a Cidade do Agro”.",
  "legenda": "Marcas que apoiam Cidade do Agro\n\n@cropchembrasil \n\n@elfaroadvising \n\nExtremo Sul\n\n@invictafertilizer \n\n@gelateriacono \n\n#cropchem #elfaro #extremosul #invicta #cono",
  "data": "2026-07-11",
  "codigo": "Dap-m6dkQmS",
  "logo": "assets/logos/cropchem.png",
  "arte": "assets/posts/post-23-1.jpg"
 },
 {
  "id": "el-faro",
  "nome": "El Faro Advising",
  "instagram": "elfaroadvising",
  "area": "Consultoria e gestão",
  "selo": "prata",
  "post": "23.2",
  "carrossel": true,
  "frase": null,
  "texto": "Marca apresentada no carrossel “Marcas que apoiam a Cidade do Agro”.",
  "legenda": "Marcas que apoiam Cidade do Agro\n\n@cropchembrasil \n\n@elfaroadvising \n\nExtremo Sul\n\n@invictafertilizer \n\n@gelateriacono \n\n#cropchem #elfaro #extremosul #invicta #cono",
  "data": "2026-07-11",
  "codigo": "Dap-m6dkQmS",
  "logo": "assets/logos/el-faro.png",
  "arte": "assets/posts/post-23-2.jpg"
 },
 {
  "id": "extremo-sul",
  "nome": "Extremo Sul Cooperativa Arrozeira",
  "instagram": null,
  "area": "Cooperativas",
  "selo": "prata",
  "post": "23.3",
  "carrossel": true,
  "frase": null,
  "texto": "Marca apresentada no carrossel “Marcas que apoiam a Cidade do Agro”.",
  "legenda": "Marcas que apoiam Cidade do Agro\n\n@cropchembrasil \n\n@elfaroadvising \n\nExtremo Sul\n\n@invictafertilizer \n\n@gelateriacono \n\n#cropchem #elfaro #extremosul #invicta #cono",
  "data": "2026-07-11",
  "codigo": "Dap-m6dkQmS",
  "logo": "assets/logos/extremo-sul.png",
  "arte": "assets/posts/post-23-3.jpg"
 },
 {
  "id": "invicta",
  "nome": "Invicta Fertilizer",
  "instagram": "invictafertilizer",
  "area": "Nutrição de cultivos",
  "selo": "prata",
  "post": "23.4",
  "carrossel": true,
  "frase": null,
  "texto": "Marca apresentada no carrossel “Marcas que apoiam a Cidade do Agro”.",
  "legenda": "Marcas que apoiam Cidade do Agro\n\n@cropchembrasil \n\n@elfaroadvising \n\nExtremo Sul\n\n@invictafertilizer \n\n@gelateriacono \n\n#cropchem #elfaro #extremosul #invicta #cono",
  "data": "2026-07-11",
  "codigo": "Dap-m6dkQmS",
  "logo": "assets/logos/invicta.png",
  "arte": "assets/posts/post-23-4.jpg"
 },
 {
  "id": "cono",
  "nome": "Cono Gelateria Autoral",
  "instagram": "gelateriacono",
  "area": "Alimentos e gastronomia",
  "selo": "prata",
  "post": "23.5",
  "carrossel": true,
  "frase": null,
  "texto": "Marca apresentada no carrossel “Marcas que apoiam a Cidade do Agro”.",
  "legenda": "Marcas que apoiam Cidade do Agro\n\n@cropchembrasil \n\n@elfaroadvising \n\nExtremo Sul\n\n@invictafertilizer \n\n@gelateriacono \n\n#cropchem #elfaro #extremosul #invicta #cono",
  "data": "2026-07-11",
  "codigo": "Dap-m6dkQmS",
  "logo": "assets/logos/cono.png",
  "arte": "assets/posts/post-23-5.jpg"
 },
 {
  "id": "dagramas",
  "nome": "Dagramas",
  "instagram": "dagramas",
  "area": "A confirmar",
  "selo": "bronze",
  "post": "24.1",
  "carrossel": true,
  "frase": null,
  "texto": "Marca apresentada no carrossel “Marcas que apoiam a Cidade do Agro”.",
  "legenda": "Marcas que apoiam a Cidade do Agro \n\n@dagramas \n\n@estanciacapororoca \n\n@slcmaquinasjohndeere \n\n@cropsteam \n\n@brasa.emcasa \n\n#dagramas #capororoca #slcjohndeere #cropsteam #brasaemcasa",
  "data": "2026-07-11",
  "codigo": "DaqB7Y4EdLf",
  "logo": "assets/logos/dagramas.png",
  "arte": "assets/posts/post-24-1.jpg"
 },
 {
  "id": "estancia-capororoca",
  "nome": "Estância Capororoca",
  "instagram": "estanciacapororoca",
  "area": "Produtores rurais",
  "selo": "bronze",
  "post": "24.2",
  "carrossel": true,
  "frase": null,
  "texto": "Marca apresentada no carrossel “Marcas que apoiam a Cidade do Agro”.",
  "legenda": "Marcas que apoiam a Cidade do Agro \n\n@dagramas \n\n@estanciacapororoca \n\n@slcmaquinasjohndeere \n\n@cropsteam \n\n@brasa.emcasa \n\n#dagramas #capororoca #slcjohndeere #cropsteam #brasaemcasa",
  "data": "2026-07-11",
  "codigo": "DaqB7Y4EdLf",
  "logo": "assets/logos/estancia-capororoca.png",
  "arte": "assets/posts/post-24-2.jpg"
 },
 {
  "id": "slc-john-deere",
  "nome": "SLC Máquinas (John Deere)",
  "instagram": "slcmaquinasjohndeere",
  "area": "Máquinas agrícolas",
  "selo": "bronze",
  "post": "24.3",
  "carrossel": true,
  "frase": null,
  "texto": "Marca apresentada no carrossel “Marcas que apoiam a Cidade do Agro”.",
  "legenda": "Marcas que apoiam a Cidade do Agro \n\n@dagramas \n\n@estanciacapororoca \n\n@slcmaquinasjohndeere \n\n@cropsteam \n\n@brasa.emcasa \n\n#dagramas #capororoca #slcjohndeere #cropsteam #brasaemcasa",
  "data": "2026-07-11",
  "codigo": "DaqB7Y4EdLf",
  "logo": "assets/logos/slc-john-deere.png",
  "arte": "assets/posts/post-24-3.jpg"
 },
 {
  "id": "brasa-em-casa",
  "nome": "Brasa em Casa",
  "instagram": "brasa.emcasa",
  "area": "Alimentos e gastronomia",
  "selo": "bronze",
  "post": "24.5",
  "carrossel": true,
  "frase": null,
  "texto": "Marca apresentada no carrossel “Marcas que apoiam a Cidade do Agro”.",
  "legenda": "Marcas que apoiam a Cidade do Agro \n\n@dagramas \n\n@estanciacapororoca \n\n@slcmaquinasjohndeere \n\n@cropsteam \n\n@brasa.emcasa \n\n#dagramas #capororoca #slcjohndeere #cropsteam #brasaemcasa",
  "data": "2026-07-11",
  "codigo": "DaqB7Y4EdLf",
  "logo": "assets/logos/brasa-em-casa.png",
  "arte": "assets/posts/post-24-5.jpg"
 },
 {
  "id": "irga",
  "nome": "IRGA — Instituto Rio Grandense do Arroz",
  "instagram": null,
  "area": "Instituições e entidades",
  "selo": null,
  "post": "25.1",
  "carrossel": true,
  "frase": null,
  "texto": "Marca apresentada no carrossel “Marcas que apoiam a Cidade do Agro”.",
  "legenda": "Marcas que apoiam a Cidade do Agro...\n\nIRGA RS\n@ematerrs \n@faem.ufpel \n@inovaagroufpel \n@prefcapaodoleao \n@sebraers \n@equipefieldcrops \n@fertsoil \n@aliancapelotas \n@sindapel_pelotas \n@acpelotas \n@federarroz \n@lab.nutriplant \n@phenoglad \n\n#cidadedoagro #irga #emater #faem #arrozeiros",
  "data": "2026-07-13",
  "codigo": "DavcBO5EVYQ",
  "logo": "assets/logos/irga.png",
  "arte": "assets/posts/post-25-1.jpg"
 },
 {
  "id": "emater",
  "nome": "Emater/RS",
  "instagram": "ematerrs",
  "area": "Instituições e entidades",
  "selo": null,
  "post": "25.2",
  "carrossel": true,
  "frase": null,
  "texto": "Marca apresentada no carrossel “Marcas que apoiam a Cidade do Agro”.",
  "legenda": "Marcas que apoiam a Cidade do Agro...\n\nIRGA RS\n@ematerrs \n@faem.ufpel \n@inovaagroufpel \n@prefcapaodoleao \n@sebraers \n@equipefieldcrops \n@fertsoil \n@aliancapelotas \n@sindapel_pelotas \n@acpelotas \n@federarroz \n@lab.nutriplant \n@phenoglad \n\n#cidadedoagro #irga #emater #faem #arrozeiros",
  "data": "2026-07-13",
  "codigo": "DavcBO5EVYQ",
  "logo": "assets/logos/emater.png",
  "arte": "assets/posts/post-25-2.jpg"
 },
 {
  "id": "faem-ufpel",
  "nome": "FAEM/UFPel — Faculdade de Agronomia Eliseu Maciel",
  "instagram": "faem.ufpel",
  "area": "Pesquisa e ensino",
  "selo": null,
  "post": "25.3",
  "carrossel": true,
  "frase": null,
  "texto": "Marca apresentada no carrossel “Marcas que apoiam a Cidade do Agro”.",
  "legenda": "Marcas que apoiam a Cidade do Agro...\n\nIRGA RS\n@ematerrs \n@faem.ufpel \n@inovaagroufpel \n@prefcapaodoleao \n@sebraers \n@equipefieldcrops \n@fertsoil \n@aliancapelotas \n@sindapel_pelotas \n@acpelotas \n@federarroz \n@lab.nutriplant \n@phenoglad \n\n#cidadedoagro #irga #emater #faem #arrozeiros",
  "data": "2026-07-13",
  "codigo": "DavcBO5EVYQ",
  "logo": "assets/logos/faem-ufpel.png",
  "arte": "assets/posts/post-25-3.jpg"
 },
 {
  "id": "inovagro-ufpel",
  "nome": "InovaAgro UFPel (Unidade Embrapii)",
  "instagram": "inovaagroufpel",
  "area": "Pesquisa e ensino",
  "selo": null,
  "post": "25.4",
  "carrossel": true,
  "frase": null,
  "texto": "Marca apresentada no carrossel “Marcas que apoiam a Cidade do Agro”.",
  "legenda": "Marcas que apoiam a Cidade do Agro...\n\nIRGA RS\n@ematerrs \n@faem.ufpel \n@inovaagroufpel \n@prefcapaodoleao \n@sebraers \n@equipefieldcrops \n@fertsoil \n@aliancapelotas \n@sindapel_pelotas \n@acpelotas \n@federarroz \n@lab.nutriplant \n@phenoglad \n\n#cidadedoagro #irga #emater #faem #arrozeiros",
  "data": "2026-07-13",
  "codigo": "DavcBO5EVYQ",
  "logo": "assets/logos/inovagro-ufpel.png",
  "arte": "assets/posts/post-25-4.jpg"
 },
 {
  "id": "prefeitura-capao",
  "nome": "Prefeitura de Capão do Leão",
  "instagram": "prefcapaodoleao",
  "area": "Instituições e entidades",
  "selo": null,
  "post": "25.5",
  "carrossel": true,
  "frase": null,
  "texto": "Marca apresentada no carrossel “Marcas que apoiam a Cidade do Agro”.",
  "legenda": "Marcas que apoiam a Cidade do Agro...\n\nIRGA RS\n@ematerrs \n@faem.ufpel \n@inovaagroufpel \n@prefcapaodoleao \n@sebraers \n@equipefieldcrops \n@fertsoil \n@aliancapelotas \n@sindapel_pelotas \n@acpelotas \n@federarroz \n@lab.nutriplant \n@phenoglad \n\n#cidadedoagro #irga #emater #faem #arrozeiros",
  "data": "2026-07-13",
  "codigo": "DavcBO5EVYQ",
  "logo": "assets/logos/prefeitura-capao.png",
  "arte": "assets/posts/post-25-5.jpg"
 },
 {
  "id": "sebrae",
  "nome": "Sebrae RS",
  "instagram": "sebraers",
  "area": "Instituições e entidades",
  "selo": null,
  "post": "25.6",
  "carrossel": true,
  "frase": null,
  "texto": "Marca apresentada no carrossel “Marcas que apoiam a Cidade do Agro”.",
  "legenda": "Marcas que apoiam a Cidade do Agro...\n\nIRGA RS\n@ematerrs \n@faem.ufpel \n@inovaagroufpel \n@prefcapaodoleao \n@sebraers \n@equipefieldcrops \n@fertsoil \n@aliancapelotas \n@sindapel_pelotas \n@acpelotas \n@federarroz \n@lab.nutriplant \n@phenoglad \n\n#cidadedoagro #irga #emater #faem #arrozeiros",
  "data": "2026-07-13",
  "codigo": "DavcBO5EVYQ",
  "logo": "assets/logos/sebrae.png",
  "arte": "assets/posts/post-25-6.jpg"
 },
 {
  "id": "field-crops",
  "nome": "Field Crops",
  "instagram": "equipefieldcrops",
  "area": "Pesquisa e ensino",
  "selo": null,
  "post": "25.7",
  "carrossel": true,
  "frase": null,
  "texto": "Marca apresentada no carrossel “Marcas que apoiam a Cidade do Agro”.",
  "legenda": "Marcas que apoiam a Cidade do Agro...\n\nIRGA RS\n@ematerrs \n@faem.ufpel \n@inovaagroufpel \n@prefcapaodoleao \n@sebraers \n@equipefieldcrops \n@fertsoil \n@aliancapelotas \n@sindapel_pelotas \n@acpelotas \n@federarroz \n@lab.nutriplant \n@phenoglad \n\n#cidadedoagro #irga #emater #faem #arrozeiros",
  "data": "2026-07-13",
  "codigo": "DavcBO5EVYQ",
  "logo": "assets/logos/field-crops.png",
  "arte": "assets/posts/post-25-7.jpg"
 },
 {
  "id": "fertsoil",
  "nome": "FertSoil (FAEM/UFPel)",
  "instagram": "fertsoil",
  "area": "Pesquisa e ensino",
  "selo": null,
  "post": "25.8",
  "carrossel": true,
  "frase": null,
  "texto": "Marca apresentada no carrossel “Marcas que apoiam a Cidade do Agro”.",
  "legenda": "Marcas que apoiam a Cidade do Agro...\n\nIRGA RS\n@ematerrs \n@faem.ufpel \n@inovaagroufpel \n@prefcapaodoleao \n@sebraers \n@equipefieldcrops \n@fertsoil \n@aliancapelotas \n@sindapel_pelotas \n@acpelotas \n@federarroz \n@lab.nutriplant \n@phenoglad \n\n#cidadedoagro #irga #emater #faem #arrozeiros",
  "data": "2026-07-13",
  "codigo": "DavcBO5EVYQ",
  "logo": "assets/logos/fertsoil.png",
  "arte": "assets/posts/post-25-8.jpg"
 },
 {
  "id": "alianca-pelotas",
  "nome": "Aliança Pelotas",
  "instagram": "aliancapelotas",
  "area": "Instituições e entidades",
  "selo": null,
  "post": "25.9",
  "carrossel": true,
  "frase": null,
  "texto": "Marca apresentada no carrossel “Marcas que apoiam a Cidade do Agro”.",
  "legenda": "Marcas que apoiam a Cidade do Agro...\n\nIRGA RS\n@ematerrs \n@faem.ufpel \n@inovaagroufpel \n@prefcapaodoleao \n@sebraers \n@equipefieldcrops \n@fertsoil \n@aliancapelotas \n@sindapel_pelotas \n@acpelotas \n@federarroz \n@lab.nutriplant \n@phenoglad \n\n#cidadedoagro #irga #emater #faem #arrozeiros",
  "data": "2026-07-13",
  "codigo": "DavcBO5EVYQ",
  "logo": "assets/logos/alianca-pelotas.png",
  "arte": "assets/posts/post-25-9.jpg"
 },
 {
  "id": "sindapel",
  "nome": "Sindapel — Sindicato da Indústria do Arroz de Pelotas",
  "instagram": "sindapel_pelotas",
  "area": "Instituições e entidades",
  "selo": null,
  "post": "25.10",
  "carrossel": true,
  "frase": null,
  "texto": "Marca apresentada no carrossel “Marcas que apoiam a Cidade do Agro”.",
  "legenda": "Marcas que apoiam a Cidade do Agro...\n\nIRGA RS\n@ematerrs \n@faem.ufpel \n@inovaagroufpel \n@prefcapaodoleao \n@sebraers \n@equipefieldcrops \n@fertsoil \n@aliancapelotas \n@sindapel_pelotas \n@acpelotas \n@federarroz \n@lab.nutriplant \n@phenoglad \n\n#cidadedoagro #irga #emater #faem #arrozeiros",
  "data": "2026-07-13",
  "codigo": "DavcBO5EVYQ",
  "logo": "assets/logos/sindapel.png",
  "arte": "assets/posts/post-25-10.jpg"
 },
 {
  "id": "arrozeiros-arroio-grande",
  "nome": "Associação dos Arrozeiros de Arroio Grande",
  "instagram": null,
  "area": "Instituições e entidades",
  "selo": null,
  "post": "25.11",
  "carrossel": true,
  "frase": null,
  "texto": "Marca apresentada no carrossel “Marcas que apoiam a Cidade do Agro”.",
  "legenda": "Marcas que apoiam a Cidade do Agro...\n\nIRGA RS\n@ematerrs \n@faem.ufpel \n@inovaagroufpel \n@prefcapaodoleao \n@sebraers \n@equipefieldcrops \n@fertsoil \n@aliancapelotas \n@sindapel_pelotas \n@acpelotas \n@federarroz \n@lab.nutriplant \n@phenoglad \n\n#cidadedoagro #irga #emater #faem #arrozeiros",
  "data": "2026-07-13",
  "codigo": "DavcBO5EVYQ",
  "logo": "assets/logos/arrozeiros-arroio-grande.png",
  "arte": "assets/posts/post-25-11.jpg"
 },
 {
  "id": "acp",
  "nome": "Associação Comercial de Pelotas",
  "instagram": "acpelotas",
  "area": "Instituições e entidades",
  "selo": null,
  "post": "25.12",
  "carrossel": true,
  "frase": null,
  "texto": "Marca apresentada no carrossel “Marcas que apoiam a Cidade do Agro”.",
  "legenda": "Marcas que apoiam a Cidade do Agro...\n\nIRGA RS\n@ematerrs \n@faem.ufpel \n@inovaagroufpel \n@prefcapaodoleao \n@sebraers \n@equipefieldcrops \n@fertsoil \n@aliancapelotas \n@sindapel_pelotas \n@acpelotas \n@federarroz \n@lab.nutriplant \n@phenoglad \n\n#cidadedoagro #irga #emater #faem #arrozeiros",
  "data": "2026-07-13",
  "codigo": "DavcBO5EVYQ",
  "logo": "assets/logos/acp.png",
  "arte": "assets/posts/post-25-12.jpg"
 },
 {
  "id": "federarroz",
  "nome": "Federarroz",
  "instagram": "federarroz",
  "area": "Instituições e entidades",
  "selo": null,
  "post": "25.13",
  "carrossel": true,
  "frase": null,
  "texto": "Marca apresentada no carrossel “Marcas que apoiam a Cidade do Agro”.",
  "legenda": "Marcas que apoiam a Cidade do Agro...\n\nIRGA RS\n@ematerrs \n@faem.ufpel \n@inovaagroufpel \n@prefcapaodoleao \n@sebraers \n@equipefieldcrops \n@fertsoil \n@aliancapelotas \n@sindapel_pelotas \n@acpelotas \n@federarroz \n@lab.nutriplant \n@phenoglad \n\n#cidadedoagro #irga #emater #faem #arrozeiros",
  "data": "2026-07-13",
  "codigo": "DavcBO5EVYQ",
  "logo": "assets/logos/federarroz.png",
  "arte": "assets/posts/post-25-13.jpg"
 },
 {
  "id": "nutriplant",
  "nome": "Lab. NutriPlant (UFPel)",
  "instagram": "lab.nutriplant",
  "area": "Pesquisa e ensino",
  "selo": null,
  "post": "25.14",
  "carrossel": true,
  "frase": null,
  "texto": "Marca apresentada no carrossel “Marcas que apoiam a Cidade do Agro”.",
  "legenda": "Marcas que apoiam a Cidade do Agro...\n\nIRGA RS\n@ematerrs \n@faem.ufpel \n@inovaagroufpel \n@prefcapaodoleao \n@sebraers \n@equipefieldcrops \n@fertsoil \n@aliancapelotas \n@sindapel_pelotas \n@acpelotas \n@federarroz \n@lab.nutriplant \n@phenoglad \n\n#cidadedoagro #irga #emater #faem #arrozeiros",
  "data": "2026-07-13",
  "codigo": "DavcBO5EVYQ",
  "logo": "assets/logos/nutriplant.png",
  "arte": "assets/posts/post-25-14.jpg"
 },
 {
  "id": "phenoglad",
  "nome": "Brazilian Flower Network / PhenoGlad",
  "instagram": "phenoglad",
  "area": "Pesquisa e ensino",
  "selo": null,
  "post": "25.15",
  "carrossel": true,
  "frase": null,
  "texto": "Marca apresentada no carrossel “Marcas que apoiam a Cidade do Agro”.",
  "legenda": "Marcas que apoiam a Cidade do Agro...\n\nIRGA RS\n@ematerrs \n@faem.ufpel \n@inovaagroufpel \n@prefcapaodoleao \n@sebraers \n@equipefieldcrops \n@fertsoil \n@aliancapelotas \n@sindapel_pelotas \n@acpelotas \n@federarroz \n@lab.nutriplant \n@phenoglad \n\n#cidadedoagro #irga #emater #faem #arrozeiros",
  "data": "2026-07-13",
  "codigo": "DavcBO5EVYQ",
  "logo": "assets/logos/phenoglad.png",
  "arte": "assets/posts/post-25-15.jpg"
 },
 {
  "id": "semear",
  "nome": "Semear",
  "instagram": null,
  "area": "Revendas e insumos",
  "selo": "ouro",
  "post": "26",
  "carrossel": false,
  "frase": "Com mais de 30 anos de experiência, a Semear é referência em excelência e qualidade na prestação de serviços no campo. Semeamos juntos o futuro do agro!",
  "texto": "Assistência técnica, secagem e armazenagem de grãos, insumos e sementes em Pelotas.",
  "legenda": "SEMEAR\n\nCom mais de 30 anos de história em Pelotas, a Semear é referência regional em assistência técnica, secagem e armazenagem de grãos, insumos e sementes, acompanhando o produtor do preparo do solo até a comercialização. \n \n📍 Cidade do Agro\n👉 Siga: @cidadedoagro_\n\n#CidadeDoAgro #hortifruti #AgroGaúcho #RioGrandeDoSul #InsumoAgricola",
  "data": "2026-07-15",
  "codigo": "Da0yUH6xnjw",
  "logo": "assets/logos/semear.png",
  "arte": "assets/posts/post-26.jpg"
 },
 {
  "id": "inquima",
  "nome": "Inquima",
  "instagram": null,
  "area": "Nutrição de cultivos",
  "selo": "diamante",
  "post": "27",
  "carrossel": false,
  "frase": "Mais do que produtos, a Inquima oferece serviços de excelência em aplicação e nutrição vegetal!",
  "texto": "O jeito eficiente de fazer agricultura!",
  "legenda": "INQUIMA\n\nMais do que produtos, a Inquima oferece serviços de excelência em aplicação e nutrição vegetal, com o objetivo de auxiliar o produtor a alcançar o máximo potencial dos seus cultivos!\n\n📍 Cidade do Agro\n👉 Siga: @cidadedoagro_\n\n#InovaçãoNoCampo #aplicação #cidadedoagro",
  "data": "2026-07-20",
  "codigo": "DbBQWdcR9yr",
  "logo": "assets/logos/inquima.png",
  "arte": "assets/posts/post-27.jpg"
 },
 {
  "id": "cmpc",
  "nome": "CMPC",
  "instagram": null,
  "area": "Florestal",
  "selo": "diamante",
  "post": "28",
  "carrossel": false,
  "frase": null,
  "texto": "O post traz só o logo; os temas marcados são floresta, ILPF (integração lavoura-pecuária-floresta), carbono e agricultura.",
  "legenda": "cmpc\n\n#floresta #ilpf #carbono #agricultura",
  "data": "2026-07-21",
  "codigo": "DbDok86xl-W",
  "logo": "assets/logos/cmpc.png",
  "arte": "assets/posts/post-28.jpg"
 },
 {
  "id": "sicredi",
  "nome": "Sicredi",
  "instagram": "sicredi",
  "area": "Crédito, seguros e finanças",
  "selo": "diamante",
  "post": "29",
  "carrossel": false,
  "frase": null,
  "texto": "Post de apresentação da marca no perfil da Cidade do Agro.",
  "legenda": "@sicredi \n\n📍 Cidade do Agro\n👉 Siga: @cidadedoagro_",
  "data": "2026-08-17",
  "codigo": "DcJj5OrR-xK",
  "logo": "assets/logos/sicredi.png",
  "arte": "assets/posts/post-29.jpg"
 },
 {
  "id": "transportadora-sana",
  "nome": "Transportadora Sana",
  "instagram": "transportadorasana",
  "area": "Logística",
  "selo": "diamante",
  "post": "30",
  "carrossel": false,
  "frase": null,
  "texto": "Post de apresentação da marca no perfil da Cidade do Agro.",
  "legenda": "@transportadorasana \n\n📍 Cidade do Agro\n👉 Siga: @cidadedoagro_",
  "data": "2026-08-18",
  "codigo": "DcLtY0mRAD0",
  "logo": "assets/logos/transportadora-sana.png",
  "arte": "assets/posts/post-30.jpg"
 },
 {
  "id": "r-bio",
  "nome": "R-Bio",
  "instagram": "rbio.agro",
  "area": "Nutrição de cultivos",
  "selo": "diamante",
  "post": "31",
  "carrossel": false,
  "frase": null,
  "texto": "Post de apresentação da marca no perfil da Cidade do Agro.",
  "legenda": "@rbio.agro \n\n📍 Cidade do Agro\n👉 Siga: @cidadedoagro_",
  "data": "2026-08-19",
  "codigo": "DcORo0sxgmF",
  "logo": "assets/logos/r-bio.png",
  "arte": "assets/posts/post-31.jpg"
 },
 {
  "id": "connectere",
  "nome": "Connectere AgroGestão",
  "instagram": "connectereagrogestao",
  "area": "Consultoria e gestão",
  "selo": "bronze",
  "post": "32",
  "carrossel": false,
  "frase": null,
  "texto": "Post de apresentação da marca no perfil da Cidade do Agro.",
  "legenda": "@connectereagrogestao \n\n📍 Cidade do Agro\n👉 Siga: @cidadedoagro_",
  "data": "2026-08-24",
  "codigo": "DcblIh1xd9a",
  "logo": "assets/logos/connectere.png",
  "arte": "assets/posts/post-32.jpg"
 },
 {
  "id": "duagro",
  "nome": "Duagro",
  "instagram": "duagro_",
  "area": "A confirmar",
  "selo": "prata",
  "post": "33",
  "carrossel": false,
  "frase": null,
  "texto": "Post de apresentação da marca no perfil da Cidade do Agro.",
  "legenda": "@duagro_ \n\n📍 Cidade do Agro\n👉 Siga: @cidadedoagro_",
  "data": "2026-08-24",
  "codigo": "DcbmImRx-k9",
  "logo": "assets/logos/duagro.png",
  "arte": "assets/posts/post-33.jpg"
 },
 {
  "id": "tanac",
  "nome": "Tanac",
  "instagram": "tanacoficial",
  "area": "Florestal",
  "selo": "diamante",
  "post": "34",
  "carrossel": false,
  "frase": null,
  "texto": "Post de apresentação da marca no perfil da Cidade do Agro.",
  "legenda": "@tanacoficial \n\n📍 Cidade do Agro\n👉 Siga: @cidadedoagro_",
  "data": "2026-08-25",
  "codigo": "DcdkpDFRP9H",
  "logo": "assets/logos/tanac.png",
  "arte": "assets/posts/post-34.jpg"
 },
 {
  "id": "formosa-sementes",
  "nome": "Formosa Sementes",
  "instagram": "formosasementes",
  "area": "Sementes",
  "selo": "diamante",
  "post": "35",
  "carrossel": false,
  "frase": null,
  "texto": "Post de apresentação da marca no perfil da Cidade do Agro.",
  "legenda": "@formosasementes \n\n📍 Cidade do Agro\n👉 Siga: @cidadedoagro_",
  "data": "2026-08-26",
  "codigo": "DcgXv-5R2cX",
  "logo": "assets/logos/formosa-sementes.png",
  "arte": "assets/posts/post-35.jpg"
 }
];
